USE [master]
GO

/****** Object:  Database [demoDataBase]    Script Date: 25-07-2017 17:44:30 ******/
CREATE DATABASE [demoDataBase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'demoDataBase', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\demoDataBase.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'demoDataBase_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\demoDataBase_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [demoDataBase] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [demoDataBase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [demoDataBase] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [demoDataBase] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [demoDataBase] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [demoDataBase] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [demoDataBase] SET ARITHABORT OFF 
GO

ALTER DATABASE [demoDataBase] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [demoDataBase] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [demoDataBase] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [demoDataBase] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [demoDataBase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [demoDataBase] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [demoDataBase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [demoDataBase] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [demoDataBase] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [demoDataBase] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [demoDataBase] SET  DISABLE_BROKER 
GO

ALTER DATABASE [demoDataBase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [demoDataBase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [demoDataBase] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [demoDataBase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [demoDataBase] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [demoDataBase] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [demoDataBase] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [demoDataBase] SET RECOVERY FULL 
GO

ALTER DATABASE [demoDataBase] SET  MULTI_USER 
GO

ALTER DATABASE [demoDataBase] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [demoDataBase] SET DB_CHAINING OFF 
GO

ALTER DATABASE [demoDataBase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [demoDataBase] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [demoDataBase] SET  READ_WRITE 
GO




--Tables 
USE [demoDataBase]
GO

/****** Object:  Table [dbo].[tblPerson]    Script Date: 25-07-2017 17:44:45 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[tblPerson](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Age] [int] NULL,
	[Phone] [numeric](10, 0) NOT NULL,
 CONSTRAINT [PK_tblPerson] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

